---
- name: Create new groups and user
  hosts: all
  become: true

  tasks:

    - name: Create Groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - dev
        - test

    - name: Create users
      user:
        name: "{{item.username}}"
        shell: /bin/bash
        groups: test
        append: yes
        home: "/home/{{item.homedir}}"
        with items:
          - {username: test, homedir: test}
          - {username: test1, homedir: test1}